GenerujMape
int GenerujMape.szerokosc
Referenced by CyklZycia, Generuj, KomorkiStrefy, KrokKorytarza, Strefy, WypelnijMape.
int GenerujMape.rozmiarGranicy
Referenced by Generuj.
string GenerujMape.seed
Referenced by WypelnijMape.
bool GenerujMape.seedChange
Referenced by WypelnijMape.
int [,] GenerujMape.poziom
Referenced by CyklZycia, Generuj, KomorkiStrefy, KrokKorytarza, LiczbaScian, ModyfikujMape, GenerujMape.Pokoj.Pokoj, Strefy, WypelnijMape.
int GenerujMape.udzialNapelnienia
Referenced by WypelnijMape.
int GenerujMape.wysokosc
Referenced by CyklZycia, Generuj, KomorkiStrefy, KrokKorytarza, LiczbaScian, Strefy, WypelnijMape.
int GenerujMape.liczbaIteracji
Referenced by Generuj.
int GenerujMape.liczbaPokoji
Referenced by Update.
int [,] GenerujMape.poziom2
Referenced by CyklZycia, Generuj, WypelnijMape.
int GenerujMape.liczbaPok
Referenced by ModyfikujMape, Update.
int GenerujMape.flaga
int [,] GenerujMape.mapaZgenerowana
Referenced by Start, Update.
void GenerujMape.Start()
References Generuj, mapaZgenerowana.
void GenerujMape.Update()
References Generuj, liczbaPok, liczbaPokoji, mapaZgenerowana, Wyswietl.
int [,] GenerujMape.Generuj()
References CyklZycia, liczbaIteracji, ModyfikujMape, poziom, poziom2, rozmiarGranicy, szerokosc, WypelnijMape, wysokosc.
Referenced by Start, Update.
void GenerujMape.Wyswietl(int[,] mapaOgraniczona)
Referenced by Update.
void GenerujMape.ModyfikujMape()
References liczbaPok, PolaczNajblizszePokoje, poziom, Strefy.
Referenced by Generuj.
List<List<Wspolrzedne> > GenerujMape.Strefy(int rodzaj)
References KomorkiStrefy, poziom, szerokosc, wysokosc.
Referenced by ModyfikujMape.
List<Wspolrzedne> GenerujMape.KomorkiStrefy(int poczX, int poczY)
References GenerujMape.Wspolrzedne.komorkaX, GenerujMape.Wspolrzedne.komorkaY, poziom, szerokosc, wysokosc.
Referenced by Strefy.
void GenerujMape.WypelnijMape()
References poziom, poziom2, seed, seedChange, szerokosc, udzialNapelnienia, wysokosc.
Referenced by Generuj.
void GenerujMape.PolaczNajblizszePokoje(List< Pokoj > pokoje, bool polaczanyPonownie=false)
References GenerujMape.Pokoj.czyPolaczone, GenerujMape.Wspolrzedne.komorkaX, GenerujMape.Wspolrzedne.komorkaY, GenerujMape.Pokoj.pokojePolaczone, GenerujMape.Pokoj.polaczenieZPokojemGlownym, UtworzKorytaz.
Referenced by ModyfikujMape.
void GenerujMape.UtworzKorytaz(Pokoj pokoj1, Pokoj pokoj2, Wspolrzedne komorka1, Wspolrzedne komorka2)
References KrokKorytarza, RysujProsta.
Referenced by PolaczNajblizszePokoje.
void GenerujMape.KrokKorytarza(int r, Wspolrzedne o)
References poziom, szerokosc, wysokosc.
Referenced by UtworzKorytaz.
List<Wspolrzedne> GenerujMape.RysujProsta(Wspolrzedne poczatek, Wspolrzedne koniec)
Referenced by UtworzKorytaz.
void GenerujMape.CyklZycia(int licznik, int iteracjaGraniczna)
References LiczbaScian, poziom, poziom2, szerokosc, wysokosc.
Referenced by Generuj.
int GenerujMape.LiczbaScian(int scX, int scY)
References poziom, wysokosc.
Referenced by CyklZycia.