GenerujMesh
List<Vector3> GenerujMesh.wierzсholki
Referenced by UtwMeshScian, UtworzMesze.
List<int> GenerujMesh.trojkaty
Referenced by UtworzMesze.
Dictionary<int, List<Trojkat> > GenerujMesh.trojkatDictionary
Referenced by CzyJestGranica, DodajDoSlownika, PolaczonyGranicznyWierzcholek.
List<List<int> > GenerujMesh.granicy
Referenced by ObliczGranicyMesha, RysujGranice, UtwMeshScian.
HashSet<int> GenerujMesh.wierzcholkiSprawdzone
Referenced by ObliczGranicyMesha, PolaczonyGranicznyWierzcholek.
SiatkaKwadratow GenerujMesh.siatkaKwadratow
Referenced by UtworzMesze.
MeshFilter GenerujMesh.sciany
MeshFilter GenerujMesh.poziom
void GenerujMesh.UtworzMesze(int[,] mapa, float rozmiar)
References siatkaKwadratow, Trojkatowanie, trojkaty, UtwMeshScian, wierzсholki.
void GenerujMesh.UtwMeshScian(int szerokosc, int wysokosc, float rozmiar)
References granicy, ObliczGranicyMesha, wierzсholki.
Referenced by UtworzMesze.
void GenerujMesh.DodajDoSlownika(int wierzcholekKey, Trojkat trojkat)
References trojkatDictionary.
Referenced by UtwTrojkat.
bool GenerujMesh.CzyJestGranica(int a, int b)
References trojkatDictionary.
Referenced by PolaczonyGranicznyWierzcholek.
int GenerujMesh.PolaczonyGranicznyWierzcholek(int wierzcholek)
References CzyJestGranica, trojkatDictionary, wierzcholkiSprawdzone.
Referenced by ObliczGranicyMesha, RysujGranice.
void GenerujMesh.RysujGranice(int wierzcholek, int liniaGraniczna)
References granicy, PolaczonyGranicznyWierzcholek.
Referenced by ObliczGranicyMesha.
void GenerujMesh.ObliczGranicyMesha()
References granicy, PolaczonyGranicznyWierzcholek, RysujGranice, wierzcholkiSprawdzone.
Referenced by UtwMeshScian.
void GenerujMesh.Trojkatowanie(Kwadrat kwadrat)
References GenerujMesh.Kwadrat.DL, GenerujMesh.Kwadrat.DP, GenerujMesh.Kwadrat.GL, GenerujMesh.Kwadrat.GP, GenerujMesh.Kwadrat.ksztalt, Polaczenie, GenerujMesh.Kwadrat.SD, GenerujMesh.Kwadrat.SG, GenerujMesh.Kwadrat.SL, GenerujMesh.Kwadrat.SP.
Referenced by UtworzMesze.
void GenerujMesh.Polaczenie(params Wezel[] punkty)
References Dopasuj, UtwTrojkat.
Referenced by Trojkatowanie.
void GenerujMesh.Dopasuj(Wezel[] punkty)
Referenced by Polaczenie.
void GenerujMesh.UtwTrojkat(Wezel a, Wezel b, Wezel c)
References DodajDoSlownika, GenerujMesh.Wezel.wierzcholek.
Referenced by Polaczenie.